name: Docker push develop to latest
on:
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Convert Username
        id: un
        run: echo "un=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ steps.un.outputs.un }}
          password: ${{ github.token }}
      - name: Push develop to latest
        run: |
          docker buildx imagetools create --tag ${{ steps.un.outputs.un }}/${{ github.event.repository.name }}:latest ${{ steps.un.outputs.un }}/${{ github.event.repository.name }}:${{ github.ref_name }}
          docker buildx imagetools create --tag ghcr.io/${{ steps.un.outputs.un }}/${{ github.event.repository.name }}:latest ghcr.io/${{ steps.un.outputs.un }}/${{ github.event.repository.name }}:${{ github.ref_name }}
      - name: show version
        run: |
          docker run --rm ${{ steps.un.outputs.un }}/${{ github.event.repository.name }}:latest -V
          docker run --rm ghcr.io/${{ steps.un.outputs.un }}/${{ github.event.repository.name }}:latest -V
      - name: copy curl binary
        run: |
          docker run --pull always --platform amd64 --name curl-x86_64 ${{ steps.un.outputs.un }}/${{ github.event.repository.name }}:latest
          docker cp curl-x86_64:/usr/local/bin/curl curl-x86_64
          docker run --pull always --platform arm64 --name curl-aarch64 ${{ steps.un.outputs.un }}/${{ github.event.repository.name }}:latest
          docker cp curl-aarch64:/usr/local/bin/curl curl-aarch64
      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            curl-x86_64
            curl-aarch64
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          prerelease: false
          repo_token: ${{ github.token }}
          title: ${{ steps.version.outputs.version }}
          automatic_release_tag: ${{ steps.version.outputs.version }}
          files: |
            curl-x86_64
            curl-aarch64
